# Generated by Django 2.2.4 on 2019-08-12 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('author', models.TextField()),
                ('bref_content', models.TextField()),
                ('content', models.TextField()),
                ('publish_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
